package cn.sparrow.model.common;

public enum PermissionExpressionEnum {
	IS, IS_IN, IS_ABOVE, IS_AND_ABOVE, IS_BELOW, IS_AND_BELOW, IS_SAME_LEVEL, IS_BEFORE, IS_AFTER, IS_BETWEEN, IS_CHILD,
	IS_AND_CHILD, IS_PARENT, IS_AND_PARENT, IS_CHILD_TO_PARENT, IS_AND_CHILD_TO_PARENT, IS_CHILD_TO_AND_PARENT, REGX,
	CUSTOM
}
